apiVersion: apps/v1
kind: Deployment
metadata:
  name: fearless
spec:
  selector:
    matchLabels:
      app: fearless
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: fearless
    spec:
      containers:
      - name: fearless
        image: gcr.io/none-219021/fearless-service:0.1
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Service
metadata:
  name: fearless-service
spec:
  selector:
    app: fearless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080