apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: fearless-service
spec:
  template:
    spec:
      containers:
        - image: gcr.io/none-219021/fearless-service:0.1
          env:
          - name: HOST
            value: "0.0.0.0"
          - name: STARTUP_DELAY
            value: "5s"