apiVersion: apps/v1
kind: Deployment
metadata:
  name: fearless
spec:
  selector:
    matchLabels:
      app: fearless
  replicas: 1
  template:
    metadata:
      labels:
        app: fearless
    spec:
      containers:
      - name: fearless
        image: gcr.io/none-219021/fearless-service:0.3
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: STARTUP_DELAY
          value: "5s"
        - name: RDS_SERVERNAME
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: fearless-service
spec:
  selector:
    app: fearless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080